version: "3.9"

services:
  db:
    image: postgres
    container_name: "db"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    container_name: "backend"
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    restart: "no"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db