# Generated by Django 4.1.1 on 2022-10-11 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('goal', models.TextField(verbose_name='Цель')),
                ('result', models.TextField(verbose_name='Результат')),
                ('criteria', models.TextField(verbose_name='Критерии приемки')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('max_instances', models.PositiveSmallIntegerField(default=1, verbose_name='Макс количество экземпляров проекта')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to=settings.AUTH_USER_MODEL, unique=False)),
            ],
        ),
    ]
